### ISSUE TITLE
Redirect query broken for file repo

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/roadmap#779]
url not working on login
`https://platform-ui.dev.argo.cancercollaboratory.org/file/ffaa6aa2-a69f-56f4-bdfc-0a27d93fa98b%3FisOauth%3Dtrue#`
because we have the file portion and an auth portion.

**Comment by ciaranschutte** [comment]
fixed as side effect of https://github.com/icgc-argo/platform-ui/issues/1485

**Comment by ciaranschutte** [comment]
tested in dev, looks good

**Comment by rosibaj** [comment]
Tested May 18, 2021 9:07
- This is still not working as expected. 
- I went to the file page (logged out) and clicked the login button.  I was directed to the Google Login page, where i clicked an email to login.  I was directed to a 404 page, and was `not` successfully logged in. 
- Here is a video showing the steps i completed with a failure to login: https://drive.google.com/file/d/1OkMx4GXbV-hzqDFgqzVwUduK-hA6UKJo/view
- I also tried this on the DEV environment, but the file page only resulted in this persistent flashing: 
- https://drive.google.com/file/d/1iIRge0YQQqY8PYZKNwzVGy0F5bEhMUVG/view 

@ciaranschutte I will move this one back to in progress as it is still not working.

**Comment by rosibaj** [comment]
@ciaranschutte do you have a pr to attach here for the latest changes?

**Comment by ciaranschutte** [comment]
@rosibaj no there is feedback I need to address

**Comment by ciaranschutte** [comment]
checking some code with Jon tomorrow (Jun 4th)

**Comment by ciaranschutte** [comment]
moving back to ready for impl as Dac-ui taking priority

**Comment by rosibaj** [comment]
@ciaranschutte removing from sprint.

**Comment by rosibaj** [comment]
reconfirmed Jul 12: https://platform-ui.qa.argo.cancercollaboratory.org/file/00095e36-49f6-520d-bb3a-a0ae8c31eb7e

**Comment by kcullion** [comment]
@akachru-github put this in milestone 63 as it seemed it wasn't complete. I'm not sure how urgent it is so we can always remove it

**Comment by akachru-github** [comment]
@ciaranschutte , wondering if you have any thoughts on where we left off on this ticket?

**Comment by akachru-github** [comment]
Looks like this is a dupe of what @samrichca  is working on here: https://github.com/icgc-argo/platform-ui/issues/2004

**Comment by ciaranschutte** [comment]
@akachru-github agree, looks like a dup

**Comment by kcullion** [comment]
thanks @ciaranschutte ..is it ok if we close this one? Or does it need to be released for other work?

**Comment by akachru-github** [comment]
Closing as dupe.
